---
- name: "Update packages"
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: remove unused dependencies
  become: true
  apt:
    autoremove: yes

- name: "install dependencies"
  become: yes
  apt:
    name: ["nodejs","npm","tar"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: latest

- name: "Creates directory"
  file:
    path: ~/web
    state: directory

- name: Extract backend files
  become: true
  unarchive:
    src: files/artifact.tar.gz
    dest: .
    
- name: "start app"
  become: true
  shell: |
    npm install
    pm2 stop default
    pm2 start npm --start